# Generated by Django 5.2.4 on 2025-07-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='booking_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
