# Generated by Django 5.2.4 on 2025-08-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nic',
            field=models.CharField(editable=False, max_length=13, unique=True),
        ),
    ]
