# Generated by Django 5.2.4 on 2025-07-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_add_booking_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_schedul_db4fa4_idx',
            old_name='booking_sch_c3d0b0_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_status_b99f68_idx',
            old_name='booking_status_ac0d5b_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_custome_26c44c_idx',
            old_name='booking_custome_e1c4e1_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_car_id_6559aa_idx',
            old_name='booking_car_id_c8dd23_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='booking_service_0a331e_idx',
            old_name='booking_service_f36a40_idx',
        ),
    ]
