# Generated by Django 5.2.4 on 2025-07-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_alter_customer_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
