# Generated by Django 5.2.4 on 2025-08-13 18:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_user_address_user_city_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Engine', 'Engine'), ('Exterior', 'Exterior'), ('Interior', 'Interior'), ('Electronics', 'Electronics'), ('Tires', 'Tires'), ('Cleaning', 'Cleaning'), ('Brake', 'Brake'), ('Suspension', 'Suspension'), ('Transmission', 'Transmission'), ('Exhaust', 'Exhaust'), ('Fuel', 'Fuel'), ('Tools', 'Tools')], max_length=50),
        ),
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Detailing Hub', max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(blank=True, max_length=128)),
                ('website', models.URLField(blank=True)),
                ('working_hours', models.JSONField(default=dict, help_text='Working hours for each day')),
                ('currency', models.CharField(choices=[('PKR', 'Pakistani Rupee'), ('USD', 'US Dollar')], default='PKR', max_length=3)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Settings',
                'verbose_name_plural': 'Business Settings',
                'db_table': 'business_settings',
            },
        ),
    ]
