# Generated by Django 5.2.4 on 2025-08-14 21:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_alter_product_category_businesssettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('washing', 'Washing'), ('detailing', 'Detailing'), ('maintenance', 'Maintenance'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('oil_change', 'Oil Change'), ('tire_services', 'Tire Services'), ('battery_services', 'Battery Services'), ('ac_servicing', 'Ac Servicing'), ('paint_and_body', 'Paint And Body'), ('polishing', 'Polishing'), ('modifications', 'Modifications'), ('windshield_services', 'Windshield Services'), ('engine_tuning', 'Engine Tuning'), ('breakdown_assistance', 'Breakdown Assistance')], default='maintenance', max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workshop.service')),
            ],
            options={
                'db_table': 'service_item',
            },
        ),
    ]
