# Generated by Django 5.2.4 on 2025-08-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_add_service_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='city',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterModelTable(
            name='bookingservice',
            table='booking_service',
        ),
    ]
