# Generated by Django 5.2.4 on 2025-08-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_businesssettings_city_alter_bookingservice_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
