# Generated by Django 5.2.4 on 2025-08-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nic',
        ),
    ]
