# Generated by Django 5.2.4 on 2025-07-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_invoice_grand_total_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='uuid',
            new_name='id',
        ),
    ]
