# Generated by Django 5.2.4 on 2025-08-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_remove_user_nic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
