# Generated by Django 5.2.4 on 2025-08-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax_percentage',
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
