# Generated by Django 5.2.4 on 2025-08-30 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_remove_invoice_tax_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitems',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='booking_service',
            field=models.ForeignKey(default='92f4e662-5f9d-4fd4-b64d-7f37b4df2bb2', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workshop.bookingservice'),
            preserve_default=False,
        ),
    ]
