# Generated by Django 5.2.4 on 2025-08-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_remove_invoiceitems_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='product_items_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, help_text='Positive for stock increase (restock), negative for stock decrease (sale)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity_after',
            field=models.DecimalField(decimal_places=2, help_text='Stock quantity after this movement', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity_before',
            field=models.DecimalField(decimal_places=2, help_text='Stock quantity before this movement', max_digits=10),
        ),
    ]
