# Generated by Django 5.2.4 on 2025-08-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0016_payslip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='remarks',
        ),
        migrations.AddField(
            model_name='payslip',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
