# Generated by Django 5.2.4 on 2025-08-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0017_remove_payslip_remarks_payslip_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='total_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
