# Generated by Django 5.2.4 on 2025-09-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0020_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nic',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
