name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /srv/django/Workshop/backend   # your repo path

            git pull origin main

            # Remove any existing virtual environment
            if [ -d "venv" ]; then
              echo "Removing existing virtual environment..."
              rm -rf venv
            fi

            # Create a new virtual environment
            echo "Creating virtual environment..."
            python3 -m venv venv

            # Activate the virtual environment
            source venv/bin/activate

            # Upgrade pip and install requirements
            pip install --upgrade pip
            pip install -r requirements.txt

            # Run Django migrations and collect static files
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput

            # Restart services
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx